spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:./infra/config-repo
            - file:./infra/config-repo/stats-service
            - file:./infra/config-repo/main-service
