server:
  port: 8080

spring:
  cloud:
    loadbalancer:
      cache:
        ttl: 5s
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/admin/**,/users/**,/events/**,/categories/**,/compilations/**
          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms

        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit,/stats
          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms
