server:
    port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: main-service-read
          uri: lb://main-service
          predicates:
            - Path=/admin/**,/users/**,/events/**,/categories/**,/compilations/**
            - Method=GET
          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms

        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/admin/**,/users/**,/events/**,/categories/**,/compilations/**
